### ISSUE TITLE
error when running agent1.js in html

### ISSUE THREAD

**Issue by joker9483** [Arno0x/WSC2#1]
I made a html file and in the file, I wrote as follow.
```
<html>
<head>
<script src="wsc2Agent1.js"></script>
</head>
</html>
```
When I ran it, the server show "connected", but immediately disconnected.
I am not friendly in html so please guide me to solve it.

**Comment by Arno0x** [comment]
Man, the jscript agents are not browser javascript but rather Windows Scripting Host (WSH) ! They are meant to be executed directly on the victim's machine by double clicking on it for instance, or calling them via command line:
`cscript agent.js`

See ? :)
